version: '3.8'
services:
  gateway:
    build: gateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
      - "4444:8888"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8888

  server:
    build: server
    container_name: shareit-server
    ports:
      - "9090:9090"
      - "7777:8888"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=shareit
      - SPRING_DATASOURCE_PASSWORD=shareit
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8888
      - TZ=Europe/Moscow

  db:
    image: postgres:14-alpine
    container_name: shareit-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit